apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::908867502763:user/AdminUser
      username: AdminUser
      groups:
        - system: masters
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::908867502763:role/psnodegroup-stack-NodeInstanceRole-F1ZMVS81QO52
      username: system:node:{{EC2PrivateDNSName}}
