AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CloudPassword:
    NoEcho: 'true'
    Type: String
    Description: Cloud User password
    MinLength: '1'
    MaxLength: '15'
  AppPassword:
    NoEcho: 'true'
    Type: String
    Description: App User password
    MinLength: '1'
    MaxLength: '15'
  ProdSupportPassword:
    NoEcho: 'true'
    Type: String
    Description: Prod Support User password
    MinLength: '1'
    MaxLength: '15'
Resources:
  CloudUser1:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'CloudPassword'
  CloudUser2:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'CloudPassword'
  CloudUser3:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'CloudPassword'
  CloudArchitect:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'CloudPassword'
  Director:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'CloudPassword'
  AppUser1:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'AppPassword'
  AppUser2:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'AppPassword'
  ProdSupportUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'ProdSupportPassword'
  CloudGroup:
    Type: AWS::IAM::Group
  AppGroup:
    Type: AWS::IAM::Group
  ProdSupportGroup:
    Type: AWS::IAM::Group
  CloudUsers:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'CloudGroup'
      Users: [!Ref 'CloudUser1', !Ref 'CloudUser2', !Ref 'CloudUser3', !Ref 'CloudArchitect', !Ref 'Director']
  AppUsers:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'AppGroup'
      Users: [!Ref 'AppUser1', !Ref 'AppUser2', !Ref 'Director']
  ProdSupportUsers:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'ProdSupportGroup'
      Users: [!Ref 'ProdSupportUser']
  CloudUserPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudUsers
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: '*'
          Resource: '*'
      Groups: [!Ref 'CloudGroup']
  AppUserPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AppUser
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: cloudformation:*
          Resource: '*'
      Groups: [!Ref 'AppGroup']
  ProdSupportPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ProdSupportUser
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: ['cloudformation:Describe*', 'cloudformation:List*', 'cloudformation:Get*']
          Resource: '*'
      Groups: [!Ref 'ProdSupportGroup']
