Parameters:
  MyPass:
    Type: String
  MyUser:
    Type: String
  MyGroup:
    Type: String
Resources:
  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref MyUser
      LoginProfile:
        Password: !Ref MyPass
      Groups:
        - !Sub '${MyIAMGroup1}'
    DependsOn: MyIAMGroup1
  MyIAMGroup1:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref MyGroup 
    DependsOn: MyIAMGroup2
  MyIAMGroup2:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join ["-", [ !Ref "AWS::Region", "Group2" ]]
      Policies:
        - PolicyName: MyVideoPolicy
          PolicyDocument:
             Statement:
                - Effect: Allow
                  Action:
                    - s3:Get*
                  Resource: "*"
